#%RAML 0.8
title: OICAirFlowControl
version: v1.0-20150805
schemas:
  - AirFlowControl:       !include oic.r.airflowControl.json
    AirFlowControlBatch:  !include oic.r.airflowControl-Batch.json

traits:
  - interface-all:
      queryParameters:
        if:
          enum: ["oic.if.ll", "oic.if.b"]

  - interface-b:
      queryParameters:
        if:
          enum: ["oic.if.b"]

/AirFlowControlResURI:
  description: |
    This resource describes the attributes associated with control of air flow.
    For example as modelled by a Thermostat (fan), Room A/C or other device.
    The resource is a composite resource being made up as a collection of:
      AirFlow Resource
      BinarySwitch Resource

  displayName: Air Flow Control
  is: [ interface-all ] # valid for all methods

  get:
    description: |
      Retrieves the current air flow control values.
    responses:
      200:
        body:
          application/json:
            schema: AirFlowControl
            example: |
              {
                "rt": "oic.r.airFlowControl",
                "id": "unique_example_id",
                "airFlowControl": [
                  {
                    "href": "/BinarySwitchResURI",
                    "rel":  "contains",
                    "rt":   "oic.r.switch.binary",
                    "if":   "oic.if.a"
                  },
                  {
                    "href": "/AirFlowResURI",
                    "rel":  "contains",
                    "rt":   "oic.r.airFlow",
                    "if":   "oic.if.a"
                  }
                ]
              }

  post:
    is: [interface-b]
    description: |
      Sets the current air flow control values using the batch interface
    body:
      application/json:
        schema: AirFlowControlBatch
        example: |
          {
            "id":     "unique_example_id",
            "airFlowControl": [
              {
                "id":    "unique_example_id",
                "value": true
              },
              {
                "id":         "unique_example_id",
                "direction":  "right",
                "speed":      3
              }
            ]
          }

    responses:
      200:
        body:
          application/json:
            schema: AirFlowControlBatch
            example: |
              {
                "id":     "unique_example_id",
                "airFlowControl": [
                  {
                    "id":    "unique_example_id",
                    "value": true
                  },
                  {
                    "id":        "unique_example_id",
                    "direction": "right",
                    "speed":     3
                  }
                ]
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an invalid property value for direction.
            An update with an out of range property value for speed.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: AirFlowControlBatch
            example: |
              {
                "id":     "unique_example_id",
                "airFlowControl": [
                  {
                    "id":    "unique_example_id",
                    "value": true
                  },
                  {
                    "id":         "unique_example_id",
                    "direction":  "right",
                    "speed":      3
                  }
                ]
              }
