#%RAML 0.8
title: OICAirFlow
version: v1.0-20150805
schemas:
  - AirFlow: !include oic.r.airFlow.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/AirFlowResURI:
  description: |
    This resource describes the properties associated with air flow.
    The direction is the directionality of the air flow if applicable.
    Direction values are dependent on the capabilities of the unit.
    The speed is an integer representing the current speed level for the unit.
    The range is the min,max values for the speed level.

  displayName: Air Flow
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the current air flow values.
    responses:
      200:
        body:
          application/json:
            schema: AirFlow
            example: |
              {
                "rt":         "oic.r.airFlow",
                "id":         "unique_example_id",
                "direction":  "left",
                "speed":      5,
                "range":      "1,7"
              }

  post:
    description: |
      Sets the current air flow values.
      Only direction and speed may be set by an update operation.
    body:
      application/json:
        schema: AirFlow
        example: |
          {
            "id":         "unique_example_id",
            "direction":  "right",
            "speed":      3
          }
    responses:
      200:
        body:
          application/json:
            schema: AirFlow
            example: |
              {
                "id":         "unique_example_id",
                "direction":  "right",
                "speed":      3
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an invalid property value for direction.
            An update with an out of range property value for speed.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: AirFlow
            example: |
              {
                "id":         "unique_example_id",
                "direction":  "right",
                "speed":      3
              }
