#%RAML 0.8
title: OICAirFlowControl
version: v1.1.0-20160229
documentation:
  - title: Copyright (c) 2016 Open Interconnect Consortium, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE OPEN INTERCONNECT CONSORTIUM, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE OPEN INTERCONNECT CONSORTIUM, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - AirFlowControl:       !include schemas/oic.r.airflowControl.json
  - AirFlowControlBatch:  !include schemas/oic.r.airflowControl-Batch.json

traits:
  - interface-all:
      queryParameters:
        if:
          enum: ["oic.if.ll", "oic.if.b"]

  - interface-b:
      queryParameters:
        if:
          enum: ["oic.if.b"]

/AirFlowControlResURI:
  description: |
    This resource describes the attributes associated with control of air flow.
    For example as modelled by a Thermostat (fan), Room A/C or other device.
    The resource is a composite resource being made up as a collection of:
      AirFlow Resource
      BinarySwitch Resource

  displayName: Air Flow Control
  is: [ interface-all ] # valid for all methods

  get:
    description: |
      Retrieves the current air flow control values.
    responses:
      200:
        body:
          application/json:
            schema: AirFlowControl
            example: |
              {
                "rt": "oic.r.airflowcontrol",
                "id": "unique_example_id",
                "airFlowControl": [
                  {
                    "href": "/BinarySwitchResURI",
                    "rel":  "contains",
                    "rt":   "oic.r.switch.binary",
                    "if":   "oic.if.a"
                  },
                  {
                    "href": "/AirFlowResURI",
                    "rel":  "contains",
                    "rt":   "oic.r.airflow",
                    "if":   "oic.if.a"
                  }
                ]
              }

  post:
    is: [interface-b]
    description: |
      Sets the current air flow control values using the batch interface
    body:
      application/json:
        schema: AirFlowControlBatch
        example: |
          {
            "id":     "unique_example_id",
            "airFlowControl": [
              {
                "id":    "unique_example_id",
                "value": true
              },
              {
                "id":         "unique_example_id",
                "direction":  "right",
                "speed":      3
              }
            ]
          }

    responses:
      200:
        body:
          application/json:
            schema: AirFlowControlBatch
            example: |
              {
                "id":     "unique_example_id",
                "airFlowControl": [
                  {
                    "id":    "unique_example_id",
                    "value": true
                  },
                  {
                    "id":        "unique_example_id",
                    "direction": "right",
                    "speed":     3
                  }
                ]
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an invalid property value for direction.
            An update with an out of range property value for speed.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: AirFlowControlBatch
            example: |
              {
                "id":     "unique_example_id",
                "airFlowControl": [
                  {
                    "id":    "unique_example_id",
                    "value": true
                  },
                  {
                    "id":         "unique_example_id",
                    "direction":  "right",
                    "speed":      3
                  }
                ]
              }
