#%RAML 0.8
title: OICAutoFocus
version: v1.0.0-20151223
documentation:
  - title: © 2016 Open Interconnect Consortium, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
         
        THIS SOFTWARE IS PROVIDED BY THE OPEN INTERCONNECT CONSORTIUM, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE OPEN INTERCONNECT CONSORTIUM, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - AutoFocus: !include schemas/oic.r.autofocus.json
traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.a"]

/AutoFocusResURI:
  description: |
    This resource describes an auto focus on/off feature (on/off).
    The value is a boolean.
    An AutoFocus value of 'true' means that the switch is on.
    An AutoFocus value of 'false' means that the switch is off.
    Note that when PTZ is used the autofocus works only the selected area.
  displayName: Auto Focus
  is: [ interface ]

  get:
    responses:
      200:
        body:
          application/json:
            schema: AutoFocus
            example: |
              {
                "rt":         "oic.r.autofocus",
                "id":         "unique_example_id",
                "autoFocus":  false
              }
  post:
    body:
      application/json:
        schema: AutoFocus
        example: |
          {
            "id":         "unique_example_id",
            "autoFocus":  true
          }
    responses:
      200:
        body:
          application/json:
            schema: AutoFocus
            example: |
              {
                "id":         "unique_example_id",
                "autoFocus":  true
              }
