#%RAML 0.8
title: OCFColourCSC
version: OCFv1.1.0-2017
documentation:
  - title: (c) 2017 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - ColourCSC: !include oic.r.colour.csc.json

traits:
  - interface-all:
      queryParameters:
        if:
          enum: ["oic.if.a","oic.if.baseline"]

  - interface-a:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/example/ColourSpaceCoordinatesResURI:
  description: |
    This resource describes the colour using colour space co-ordinates.
    csc is the colour space coordinates in CIE colour space.
      The first item in the array is the X coordinate.
      The second item in the array is the Y coordinate.
      If precision (from oic.r.baseresource) is provided it applies to both the X and Y coordinates.

  displayName: Colour Space Coordinates

  get:
    is: [ interface-all ] # valid for all methods
    description: |
      Provides the colour using colour space coordinates.
    responses:
      200:
        body:
          application/json:
            schema: ColourCSC
            example: |
              {
                "rt":         ["oic.r.colour.csc"],
                "id":         "unique_example_id",
                "csc":        [0.41,0.51]
              }

  post:
    is: [ interface-a ] # valid for all methods
    description: |
      Sets current colour space coordinates
    body:
      application/json:
        schema: ColourCSC
        example: |
          {
            "id":         "unique_example_id",
            "csc":        [0.40,0.70]
          }
    responses:
      200:
        body:
          application/json:
            schema: ColourCSC
            example: |
              {
                "id":          "unique_example_id",
                "csc":         [0.40,0.70]
              }
