#%RAML 0.8
title: OICConsumables
version: OCF-v1.0.0-20160620
documentation:
  - title: Copyright (c) 2017 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - consumables: !include oic.r.consumablecollection.json
  - consumables-ll: !include oic.r.consumablecollection-ll.json

traits:
  - interface-baseline:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

  - interface-ll:
      queryParameters:
        if:
            enum: ["oic.if.ll"]


/ConsumablesBaselineResURI:
  description: |
    This resource specifies things that can be consumed such as filter material, printer toner etc
    The resource is a collection of instances of oic.r.consumable detailing the individual consumed items
    supportedconsumables is the set of consumable types that this instance of the Resource supports

  displayName: Consumable Collection
  is: [ interface-baseline ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: consumables
            example: |
              {
                "rt":               ["oic.r.consumablecollection","oic.wk.col"],
                "id":               "unique_example_id",
                "rts":              ["oic.r.consumable","oic.r.value.conditional"],
                "supportedconsumables": ["tonerBlack","tonerCyan","tonerMagenta","tonerYellow"],
                "links": [
                  {"href": "/myTonerBlackResURI", "rt": ["oic.r.consumable"], "if": ["oic.if.s","oic.if.baseline"]},
                  {"href": "/myTonerCyanResURI", "rt": ["oic.r.consumable"], "if": ["oic.if.s","oic.if.baseline"]},
                  {"href": "/myTonerMagentaResURI", "rt": ["oic.r.consumable"], "if": ["oic.if.s","oic.if.baseline"]},
                  {"href": "/myTonerYellowResURI", "rt": ["oic.r.consumable"], "if": ["oic.if.s","oic.if.baseline"]}
                ]
              }

/ConsumablesLLResURI:
  description: |
    This resource specifies things that can be consumed such as filter material, printer toner etc
    The resource is a collection of instances of oic.r.consumable detailing the individual consumed items
    supportedconsumables is the set of consumable types that this instance of the Resource supports

  displayName: Consumables
  is: [ interface-ll ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: consumables-ll
            example: |
              {
                "links": [
                  {"href": "/myTonerBlackResURI", "rt": ["oic.r.consumable"], "if": ["oic.if.s","oic.if.baseline"]},
                  {"href": "/myTonerCyanResURI", "rt": ["oic.r.consumable"], "if": ["oic.if.s","oic.if.baseline"]},
                  {"href": "/myTonerMagentaResURI", "rt": ["oic.r.consumable"], "if": ["oic.if.s","oic.if.baseline"]},
                  {"href": "/myTonerYellowResURI", "rt": ["oic.r.consumable"], "if": ["oic.if.s","oic.if.baseline"]}
                ]
              }
