#%RAML 0.8
title: OICDRLC
version: v1.1.0-20160519
documentation:
  - title: (c) 2016, 2018 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - DRLC:           !include oic.r.energy.drlc.json
  - CreateResponse: !include oic.create.json
traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.b","oic.if.baseline"]


/DRLCResURI:
  description: |
    This resource describes any to be applied or currently being applied DRLC signal.
    The DRType is the ApplianceLoadReductionType defined in Zigbee/HA Smart Energy Profile 2.0.
    Start is a string containing an ISO8601 encoded start time.
    The duration value is in minutes.
    Override indicates whether the consumer has overridden the request (true) or not (false).
    drlevel is an integer value which indicates the level/strength of required load shed/DR response from the Device; [0:0%,1:30%,2:50%,3:70%].
    mandate is a boolean that indicates whether the User can override the DR request
  displayName: Demand Response Load Control (DRLC).

  is: [ interface ]

  get:
    description: |
      Provides the current DRLC action that is being applied.
    responses:
      200:
        body:
          application/json:
            schema: DRLC
            example: |
              {
                "rt":       ["oic.r.energy.drlc"],
                "id":       "unique_example_id",
                "DRType":   1,
                "start":    "2015-01-09T16:45Z",
                "duration": 10,
                "override": false,
                "drlevel":  1,
                "mandate":  false
              }

  put:
    description: |
      Provides the DRLC action to be applied to the device or updates an existing action.
    body:
      application/json:
        schema: DRLC
        example: |
          {
            "rt":       ["oic.r.energy.drlc"],
            "id":       "unique_example_id",
            "DRType":   1,
            "start":    "2015-01-09T16:45Z",
            "duration": 10,
            "drlevel": 1,
            "mandate": false
          }

    responses:
      200:
        description: |
          Indicates that the target DRLC resource was changed.
          The new resource attributes are provided in the response.
        body:
          application/json:
            schema: DRLC
            example: |
              {
                "DRType":   1,
                "id":       "unique_example_id",
                "start":    "2015-01-09T17:00Z",
                "duration": 15,
                "override": false,
                "drlevel": 1,
                "mandate": false
              }

      201:
        description: |
          Indicates successful creation of the DRLC resource with the attributes provided.
          The response includes the URI of the created resource.
        body:
          application/json:
            schema: CreateResponse
            example: |
              {
                "ResURI":   "/MyDevice/MyDRLCURI"
              }
