#%RAML 0.8
title: OICEnergyUsage
version: v1.1.0-20160519
documentation:
  - title: © 2016, 2017 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - Usage: !include oic.r.energy.usage.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.ll","oic.if.b","oic.if.baseline"]

/EnergyUsageResURI:
  description: |
    This resource describes a cumulative time-based energy usage query..
    The resource is a composite resource being made up as a collection of:
      TimePeriod Resource
      EnergyConsumption Resource

  displayName: Energy Usage
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the energy usage information as a composite of consumption over time.
    responses:
      200:
        body:
          application/json:
            schema: Usage
            example: |
              {
                "rt": ["oic.r.energy.usage"],
                "id": "unique_example_id",
                "resources": [
                  {
                    "href": "/TimeIntervalResURI",
                    "rel":  "contains",
                    "rt":   ["oic.r.time.period"],
                    "if":   ["oic.if.a"],
                    "eps":  [{"ep": "coaps://[fe80::b1d6]:1122"}]
                  },
                  {
                    "href": "/EnergyConsumptionResURI",
                    "rel":  "contains",
                    "rt":   ["oic.r.energy.consumption"],
                    "if":   ["oic.if.s"],
                    "eps":  [{"ep": "coaps://[fe80::b1d6]:1122"}]
                  }
                ]
              }
