#%RAML 0.8
title: OICGenericSensor
version: v1.0-20150727
schemas:
  - Sensor: !include oic.r.sensor.json
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.s"]

/GenericSensorResURI:
  description: |
    This resource describes whether some value or property or entity has been sensed or not.
    The value is a boolean.
    A value of True means that the target has been sensed.
    A value of False means that the target has not been sensed.

  displayName: Generic Sensor
  is: [ interface ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: Sensor
            example: |
              {
                "rt":    "oic.r.sensor",
                "id":    "unique_example_id",
                "value": true
              }
