#%RAML 0.8
title: OICGeolocation
version: v1.1.1-20181004
documentation:
  - title: © 2016-2018 Open Interconnect Consortium, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE OPEN INTERCONNECT CONSORTIUM, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE OPEN INTERCONNECT CONSORTIUM, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - Geolocation: !include oic.r.sensor.geolocation.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.s","oic.if.baseline"]

/GeolocationResURI:
  description: |
    This resource describes the properties associated with the current geolocation coordinate.
    Geolocation is a geolocation coordinate data.
    Latitude is a device's current Latitude coordinate (degrees).
    Longitude is a device's current Longitude coordinate (degrees).
    Alt is a device's current distance (metres) above or below 'local' sea-level.
    Accuracy is the accuracy level of the latitude and longitude coordinates (metres).
    altitudeAccuracy is the accuracy level of the altitude coordinates (metres).
    heading is a direction of travel of device (degree).
    speed is a device's current velocity (metres per second).
  displayName: Geolocation
  is: [ interface ]

  get:
    description: |
      Retrieves the current geolocation coordinates.
    responses:
      200:
        body:
          application/json:
            schema: Geolocation
            example: |
              {
                "rt":         ["oic.r.sensor.geolocation"],
                "id":         "unique_example_id",
                "latitude":  55.070859,
                "longitude": -3.60512,
                "alt": 12.07,
                "accuracy": 65.0,
                "altitudeAccuracy": 0.0,
                "heading": 90.0,
                "speed": 0.0
              }
