#%RAML 0.8
title: OICHeatingZone
version: OCF1.0-20160722
documentation:
  - title: © 2016 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - HeatingZone:  !include oic.r.heatingzonecollection.json
  - HeatingZone-ll:  !include oic.r.heatingzonecollection-ll.json

traits:
    - interface-all:
        queryParameters:
          if:
            enum: ["oic.if.ll","oic.if.baseline"]
          
    - interface-baseline:
        queryParameters:
          if:
            enum: ["oic.if.baseline"]

    - interface-ll:
        queryParameters:
          if:
             enum: ["oic.if.ll"]

/HeatingZoneResURI?if=oic.if.baseline:
  description: |
    This Resource provides information about the status of the heating zones of a Cook-Top.
    It describes the case of a Cook-Top whose zones can be activated dynamically (i.e. the device implements pot recognition).
    The resource is a collection of instances of oic.r.heatingzone detailing the individual cooktop zones

  displayName: Heating Zone Collection
  is: [ interface-baseline ] # valid for all methods

  get:
    description: |
      Retrieves the current heating zone information.
    responses:
      200:
        body:
          application/json:
            schema: HeatingZone
            example: |
              {
                "rt":    ["oic.r.heatingzonecollection","oic.wk.col"],
                "id":    "unique_example_id",
                "links": [
                  {"href": "/myZone1ResURI", "rt": ["oic.r.heatingzone"], "if": ["oic.if.s","oic.if.baseline"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/myZone2ResURI", "rt": ["oic.r.heatingzone"], "if": ["oic.if.s","oic.if.baseline"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/myZone3ResURI", "rt": ["oic.r.heatingzone"], "if": ["oic.if.s","oic.if.baseline"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/myZone4ResURI", "rt": ["oic.r.heatingzone"], "if": ["oic.if.s","oic.if.baseline"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]}
                ]
              }

/HeatingZoneResURI?if=oic.if.ll:
  description: |
    This Resource provides information about the status of the heating zones of a Cook-Top.
    It describes the case of a Cook-Top whose zones can be activated dynamically (i.e. the device implements pot recognition).
    The resource is a collection of instances of oic.r.heatingzone detailing the individual cooktop zones

  displayName: Heating Zone Collection
  is: [ interface-ll ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: HeatingZone-ll
            example: |
              [
                  {"href": "/myZone1ResURI", "rt": ["oic.r.heatingzone"], "if": ["oic.if.s"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/myZone2ResURI", "rt": ["oic.r.heatingzone"], "if": ["oic.if.s"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/myZone3ResURI", "rt": ["oic.r.heatingzone"], "if": ["oic.if.s"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/myZone4ResURI", "rt": ["oic.r.heatingzone"], "if": ["oic.if.s"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]}
               ]
