#%RAML 0.8
title: OICHumidity
version: v1.1.0-20160519
documentation:
  - title: © 2016 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - Humidity:       !include oic.r.humidity.json
  - HumidityUpdate: !include oic.r.humidity-Update.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a","oic.if.s","oic.if.baseline"]

/HumidityResURI:
  description: |
    This resource describes a sensed or desired humidity.
    The value humidity is an integer describing the percentage measured relative humidity.
    The value desiredHumidity is an integer showing the desired target relative humidity.

  displayName: Humidity
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the current (relative) humidity level.
    responses:
      200:
        body:
          application/json:
            schema: Humidity
            example: |
              {
                "rt":               ["oic.r.humidity"],
                "id":               "unique_example_id",
                "humidity":         40,
                "desiredHumidity":  40
              }

  post:
    description: |
      Sets the desired relative humidity level.
    body:
      application/json:
        schema: HumidityUpdate
        example: |
          {
            "id":               "unique_example_id",
            "desiredHumidity" : 45
          }

    responses:
      200:
        description: |
          Indicates that the relative humidity level was changed.
          The new relative humidity level is provided in the response.
        body:
          application/json:
            schema: HumidityUpdate
            example: |
              {
                "id":              "unique_example_id",
                "desiredHumidity": 45
              }
