#%RAML 0.8
title: OICIceMaker
version: v1.0-20150727
schemas:
  - IceMaker:       !include oic.r.iceMaker.json
    IceMakerUpdate: !include oic.r.iceMaker-Update.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/IceMakerResURI:
  description: |
    This resource describies an Ice Maker.
    The status is a string containing a value from the set of possible ice maker statuses.
    The possible statuses are defined by the enumeration [on, off, full]
    A status of 'on' means that the Ice Maker is operating.
    A status of 'off' means that the Ice Maker is not operating.
    A status of 'full' means that the ice collection bin is full (Ice Maker is operating).

  displayName: Ice Maker
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the current Ice Maker status.
    responses:
      200:
        body:
          application/json:
            schema: IceMaker
            example: |
              {
                "rt":     "oic.r.iceMaker",
                "id":     "unique_example_id",
                "status": "on"
              }

  post:
    description: |
      Sets the desired Ice Maker status.
      Only valid settings for status in a Post shall be [on,off].
    body:
      application/json:
        schema: IceMakerUpdate
        example: |
          {
            "id":     "unique_example_id",
            "status": "off"
          }

    responses:
      200:
        description: |
          Indicates that the Ice Maker status was changed.
          The new status  is provided in the response.
        body:
          application/json:
            schema: IceMakerUpdate
            example: |
              {
                "id":     "unique_example_id",
                "status": "off"
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an invalid property value for status.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: IceMakerUpdate
            example: |
              {
                "id":     "unique_example_id",
                "status": "off"
              }
