#%RAML 0.8
title: OICMediaSourceList
version: v1.1.0-20160229
documentation:
  - title: Copyright (c) 2016 Open Interconnect Consortium, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE OPEN INTERCONNECT CONSORTIUM, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE OPEN INTERCONNECT CONSORTIUM, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - mediaSourceList: !include oic.r.mediaSourceList.json

traits:
  - interface:
      queryParameters:
        if:
          enum: [ "oic.if.a" ]

/mediaSourceListResURI:
  description: |
    This resource provides the list of media sources available on the device.
    The sources are an array of mediaSource(s) as separately defined.
    The basic resource type oic.r.mediaSourceList does not provide any indications whether the source is input or output.
    Hence, two specializations of this resource exist.
    When a device exposes input sources then an instance of this resource with a resource type of oic.r.media.input is exposed.
    When a device exposes output sources then an instance of this resource with a resource type of oic.r.media.output is exposed.
    A device that exposes both input and output media sources then exposes two instances of this resource,
    one with a resource type or oic.r.media.input and one with a resource type of oic.r.media.output

  displayName: Media Source List
  is: [ interface ]
  get:
    responses:
      200:
        body:
          application/json:
            schema: mediaSourceList
            example: |
              {
                "rt": "oic.r.mediasourcelist",
                "id": "unique_example_id",
                "sources": [
                  {
                    "sourceName": "HDMI-CEC",
                    "sourceNumber": "1",
                    "sourceType": "audioPlusVideo",
                    "status": true
                  },
                  {
                    "sourceName": "dualRCA",
                    "sourceNumber": "1",
                    "sourceType": "audioOnly",
                    "status": false
                  }
                ]
              }

  post:
    description: |
      Changes the status of the source(s).
      Allows changes of the sourceName and the status.
    body:
      application/json:
        schema: mediaSourceList
        example: |
          {
            "id":     "unique_example_id",
            "sources": [
              {
               "sourceName":    "my new name",
               "sourceNumber":  "1",
               "status":        true
              }
            ]
          }
    responses:
      200:
        body:
          application/json:
            schema: mediaSourceList
            example: |
              {
                "id":     "unique_example_id",
                "sources": [
                  {
                    "sourceName":   "my new name",
                    "sourceNumber": "1",
                    "status":       true
                  }
                ]
              }
