#%RAML 0.8
title: OICMedia
version: v1.0.0-20151223
documentation:
  - title: © 2016 Open Interconnect Consortium, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
         
        THIS SOFTWARE IS PROVIDED BY THE OPEN INTERCONNECT CONSORTIUM, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE OPEN INTERCONNECT CONSORTIUM, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - Media: !include oic.r.media.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.s"]

/MediaResURI:
  description: |
    This resource specifies the media that an OIC Server (Camera) supports.
    The resource is an array of media elements.  Each element contains:
        A URL at which the specified media type can be accessed.
        A string array containing the definition of the media using SDP.
        Each entry in the sdp array is an SDP line.
        Each line shall follow the SDP description syntax as defined in the SDP specification.
    The SDP specification can be found at http://tools.ietf.org/html/rfc4566.
    The mime subtype video/H264 indicates video resource and the mime subtype video/jpeg indicates still image resource.

  displayName: Media
  is: [ interface ]

  get:
    description: |
      Retrieves the current media resource.
    responses:
      200:
        body:
          application/json:
            schema: Media
            example: |
              {
                "rt": "oic.r.media",
                "id": "unique_example_id",
                "media": [
                  {
                    "url": "some example url",
                    "sdp": [
                      "m=video 1 RTP/AVP 96",
                      "a=rtpmap:96 H264/9000",
                      "a=fmtp:96 profile-level-id=42A028;packetization-mode=1"
                    ]
                  },
                  {
                    "url": "some other example1 url",
                    "sdp": [
                      "m=audio 2 RTP/AVP 97",
                      "a=rtpmap:97 MP4A-LATM/90000"
                    ]
                  },
                  {
                    "url": "some other example2 url",
                    "sdp": [
                      "m=video 3 RTP/AVP 98",
                      "a=rtpmap:98 jpeg/90000",
                      "a=fmtp:98 sampling=YCbCr-4:2:0;width=256;height=256"
                    ]
                  }
                ]
              }
