#%RAML 0.8
title: OICMode
version: v1.0-20150727
schemas:
  - Mode:       !include oic.r.mode.json
    ModeUpdate: !include oic.r.mode-Update.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/ModeResURI:
  description: |
    This resource describes the modes of operation that a device can provide.
    The mode can be read or set.
    The supportedModes is a comma separated list of possible modes the device supports.
    The modes are a comma separated list of the currently active mode(s).

  displayName: Mode
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the current mode.
    responses:
      200:
        body:
          application/json:
            schema: Mode
            example: |
              {
                "rt":             "oic.r.mode",
                "id":             "unique_example_id",
                "supportedModes": "home,away,quiet,sleep",
                "modes":          "quiet"
              }

  post:
    description: |
      Sets the desired mode.
    body:
      application/json:
        schema: ModeUpdate
        example: |
          {
            "id":    "unique_example_id",
            "modes": "sleep"
          }
    responses:
      200:
        body:
          application/json:
            schema: ModeUpdate
            example: |
              {
                "id":    "unique_example_id",
                "modes": "sleep"
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an value for mode that is not found in supportedModes.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: Mode
            example: |
              {
                "id":             "unique_example_id",
                "supportedModes": "home,away,quiet,sleep",
                "modes":          "quiet"
              }
