#%RAML 0.8
title: OCF Configuration
version: v1-20160622
documentation:

  - title: OCF Copyright
    content: Copyright (c) 2016, 2017 Open Connectivity Foundation, Inc. All rights reserved.
  - title: OCF License
    content: !include LICENSE.md
  - title: OCF Disclaimer
    content: !include DISCLAIMER.md


schemas:
  - Configuration: !include schemas/oic.wk.con-schema.json
  - Update: !include schemas/oic.wk.con-Update-schema.json

traits:
  - interface-all:
      queryParameters:
        if:
          enum: ["oic.if.rw", "oic.if.baseline"]
  - interface-rw:
      queryParameters:
        if:
          enum: ["oic.if.rw"]

/example/DeviceConfigurationResURI:
  displayName: Device Configuration
  description: |
    Resource that allows for Device specific information to be configured.

  get:
    is: ["interface-all"]
    description: |
      Retrieves the current Device configuration settings
    responses:
      200:
        body:
          application/json:
            schema: Configuration
            example: |
              {
                "n":    "My Friendly Device Name",
                "rt":   ["oic.wk.con"],
                "loc":  [32.777,-96.797],
                "locn": "My Location Name",
                "c":    "USD",
                "r":    "MyRegion",
                "dl":   "en"
              }

  post:
    is: ["interface-rw"]
    description: |
      Update the information about the Device
    body:
        application/json:
            schema: Update
            example: |
                {
                  "n": "Nuevo Nombre Amistoso",
                  "r": "MyNewRegion",
                  "ln": [ { "language": "es", "value": "Nuevo Nombre Amistoso" } ],
                  "dl": "es"
                }
    responses:
      200:
        body:
          application/json:
            schema: Update
            example: |
              {
                  "n": "Nuevo Nombre Amistoso",
                  "r": "MyNewRegion",
                  "ln": [ { "language": "es", "value": "Nuevo Nombre Amistoso" } ],
                  "dl":   "es"
              }
