#%RAML 0.8
title: OICOpenLevel
version: v1.0-20150727
schemas:
  - OpenLevel: !include oic.r.openLevel.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/OpenLevelResURI:
  description: |
    This resource describes how open or ajar an entity such as a window, door, blind or shutter is.
    The openLevel can be read (acting as a sensor).
    The openLevel can also be set (acting as an actuator).
    The openLevel is device dependent across the range provided.
    If no range is provided then 0 to 100 is assumed.
    0 means closed, 100 means fully open.
    If a range is provided the lower bound=closed, upper bound=open.
    The increment is the step between possible values; if not provide 1 is assumed.

  displayName: Open Level
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the current openLevel.
    responses:
      200:
        body:
          application/json:
            schema: OpenLevel
            example: |
              {
                "rt":         "oic.r.openLevel",
                "id":         "unique_example_id",
                "openLevel":  50,
                "increment":  2,
                "range":      "0,100"
              }

  post:
    description: |
      Sets the desired openLevel.
    body:
      application/json:
        schema: OpenLevel
        example: |
          {
            "id":         "unique_example_id",
            "openLevel":  0
          }
    responses:
      200:
        body:
          application/json:
            schema: OpenLevel
            example: |
              {
                "id":         "unique_example_id",
                "openLevel":  0
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an out of range property value for openLevel.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: OpenLevel
            example: |
              {
                "id":         "unique_example_id",
                "openLevel":  50,
                "increment":  2,
                "range":      "0,100"
              }
