#%RAML 0.8
title: OICOperation
version: v1.0-20150805
schemas:
  - Operation:        !include oic.r.operational.state.json
    OperationUpdate:  !include oic.r.operational.state-Update.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/OperationalStateResURI:
  description: |
    This resource describes the operational and job states on a device.
    The states can be read or set, setting indicates a desired state.
    A device may reject an attempt to set a state that would result
    in adverse operational characteristics.
    The machineStates is a comma separated list of the possible operational states.
    The currentMachineState is the current state of operation of the device.
    The jobStates is a comma separated list of the possible job states.
    The currentJobState is the currently active jobState.
    The runningTime is the ISO8601 encoded elapsed time in the current operational state.
    The remainingTime is the ISO8601 encoded time till completion of the current operational state.
    The progressPercentage is the percentage completeness of the current jobState.

  displayName: Operational State
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the current operational and job states.
    responses:
      200:
        body:
          application/json:
            schema: Operation
            example: |
              {
                "rt":                   "oic.r.operational.state",
                "id":                   "unique_example_id",
                "machineStates":        "pause, standby, ready, active",
                "currentMachineState":  "active",
                "jobStates":            "pre-wash, wash, rinse, spin, dry, air-dry, wrinkle-prevent",
                "currentJobState":      "rinse",
                "runningTime":          "PT15M20S",
                "remainingTime":        "PT10M40S",
                "progressPercentage":    75
              }

  post:
    description: |
      Sets the desired operational or job state.
    body:
      application/json:
        schema: OperationUpdate
        example: |
          {
            "id":                   "unique_example_id",
            "currentMachineState":  "pause",
            "currentJobState":      "wash"
          }
    responses:
      200:
        body:
          application/json:
            schema: OperationUpdate
            example: |
              {
                "id":                   "unique_example_id",
                "currentMachineState":  "pause",
                "currentJobState":      "wash"
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an value for currentMachineState that is not found in machineStates.
            An update with an value for currentJobState that is not found in jobStates.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: Operation
            example: |
              {
                "id":                   "unique_example_id",
                "machineStates":        "pause, standby, ready, active",
                "currentMachineState":  "active",
                "jobStates":            "pre-wash, wash, rinse, spin, dry, air-dry, wrinkle-prevent",
                "currentJobState":      "rinse",
                "runningTime":          "PT15M20S",
                "remainingTime":        "PT10M40S",
                "progressPercentage":   75
              }
