#%RAML 0.8
title: OICPresenceSensor
version: v1.0-20150727
schemas:
  - Presence: !include oic.r.sensor.presence.json
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.s"]

/PresenceResURI:
  description: |
    This resource describes whether presence has been sensed or not.
    The value is a boolean.
    A value of True means that presence has been sensed.
    A value of False means that presence not been sensed.

  displayName: Presence Sensor
  is: [ interface ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: Presence
            example: |
              {
                "rt":    "oic.r.sensor.presence",
                "id":    "unique_example_id",
                "value": true
              }
