#%RAML 0.8
title: OICRampTime
version: v1.0-20150727
schemas:
  - RampTime: !include oic.r.light.rampTime.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/RampTimeResURI:
  description: |
    This resource that describes the Ramp Time of a dimming function.
    This specifies the actual speed of changing between 2 dimming values.
    Time is specified in milliseconds [ms].
    If the range value is not specified then the maximum value is 100 ms.
    The RampTime of 0ms indicates the minimal delay possible by the implementation.

  displayName: Ramp Time
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the current RampTime.
    responses:
      200:
        body:
          application/json:
            schema: RampTime
            example: |
              {
                "rt":       "oic.r.light.rampTime",
                "id":       "unique_example_id",
                "rampTime": 0,
                "range":    "0,100"
              }

  post:
    description: |
      Sets the current RampTime.
    body:
      application/json:
        schema: RampTime
        example: |
          {
            "id":       "unique_example_id",
            "rampTime": 50
          }
    responses:
      200:
        body:
          application/json:
            schema: RampTime
            example: |
              {
                "id":       "unique_example_id",
                "rampTime": 50
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an out of range property value for rampTime.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: RampTime
            example: |
              {
                "id":       "unique_example_id",
                "rampTime": 40
              }
