#%RAML 0.8
title: OICRules
version: v1.0-20150810
documentation:
  - title: © 2016 Open Interconnect Consortium, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
         
        THIS SOFTWARE IS PROVIDED BY THE OPEN INTERCONNECT CONSORTIUM, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE OPEN INTERCONNECT CONSORTIUM, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

schemas:
  - Collection:  !include oic.collection.json
    Rule:        !include oic.rule.json
    RuleUpdate:  !include oic.rule-Update.json
    RuleMember:  !include oic.ruleMember.json

traits:
  - interface:
      queryParameters:
        if:
            enum: ["oic.if.a", "oic.if.ll"]


/RuleListResURI:
    description: |
      Toplevel Rule resource.
      This resource is a generic collection resource
      The rts value shall contain oic.wk.rule resource types
    displayName: Rules (Top level)

    get:
        description: |
          Provides the current list of web links pointing to rules
        responses:
            200:
                body:
                    application/json:
                        schema: Collection
                        example: |
                            {
                                "rt":       "oic.wk.ruleList",
                                "n":        "list of rules",
                                "rts":      "oic.wk.rule",
                                "links": [
                                 ]
                            }

    post:
        description: |
          Provides the action to create a new rule in the ruleList resource
          The only resource type that is allowed to be created "oic.wk.rule".
          The example contains a condition, currentStatus and test.
        body:
            application/json:
                schema: Rule
                example: |
                    {
                       "condition":    "(FFFAB960-736F-46F7-BEC0-9E6CBD671ADC1:binaryswitchid:value = true) and (FFFFB960-736F-46F7-BEC0-9E6CBD671FFFF:tempid:temperature > 30)",
                       "currentStatus": "off",
                       "test":         false,
                       "rt":           "oic.wk.rule",
                       "n":            "my first rule",
                       "id":           "my_rule1",
                       "rts":          "oic.r.ruleMember",
                       "links": [
                                ]
                    }

        responses:
            200:
                description: |
                   Indicates that the target resource was created.
                   The created resource attributes are provided in the response,
                   including the server generated identifier.
                body:
                    application/json:
                       schema: Rule
                       example: |
                          {
                            "condition": "(FFFAB960-736F-46F7-BEC0-9E6CBD671ADC1:binaryswitchid:value == true) and (FFFFB960-736F-46F7-BEC0-9E6CBD671FFFF:tempid:temperature > 30)",
                            "currentStatus": "off",
                            "test":         false,
                            "rt":       "oic.wk.rule",
                            "n":        "my first rule",
                            "id":       "FFFFB960-736F-46F7-BEC0-9E6CBD671ADC1" ,
                            "rts":          "oic.r.ruleMember",
                            "links": [
                                 ]
                           }

    delete:
        description: |
          No change from collection.
          When delete is used with the URI of the collection without and query parameters then the entire collection is deleted
          When the delete uses the "ins" parameter with the value of a specific link then only that link is deleted
        queryParameters:
          ins:
              type: string
              description: |
                Delete the Web link identified by the string - could be a UUID.
              required: false
              example: |
                DELETE /mycollection?ins="FFFFB960-736F-46F7-BEC0-9E6CBD671ADC1"
        responses:
          200:
            description: The web link instance or the the entire collection has been successfully deleted
          400:
            description: The request is invalid



/RuleResURI:
    description: |
      Collection that models a rule.
      This resource is an generic collection resource with additional parameters.
      The rts value shall contain oic.wk.ruleMember resource types.
      The additional parameters are
      condition, this is the rule that will be evaluated
      currentStatus, the current state of the rule, can be "enabled, disabled, error"
      test  an trigger once activation of the rule
    displayName: Rule

    get:
        description: |
          Provides the current rule and list of web links to the rule members
        responses:
            200:
                body:
                    application/json:
                        schema: Rule
                        example: |
                           {
                              "condition": "(FFFAB960-736F-46F7-BEC0-9E6CBD671ADC1:binaryswitchid:value == true) and (FFFFB960-736F-46F7-BEC0-9E6CBD671FFFF:tempid:temperature > 30)",
                              "currentStatus": "disabled",
                              "test":     false,
                              "rt":       "oic.wk.rule",
                              "n":        "my first rule",
                              "id":       "FFFFB960-736F-46F7-BEC0-9E6CBD671ADC1",
                              "rts":          "oic.r.ruleMember",
                              "links": [
                                 ]
                           }

    put:
        description: |
          Provides the action to enable/disable the rule and an test mode for the rule.
          Calling this method with test = true will update of all ruleMembers to the prescribed membervalue.

        body:
            application/json:
                schema: RuleUpdate
                example: |
                    {
                       "currentStatus": "enabled"
                    }

        responses:
            200:
                description: |
                   Indicates that the value is changed.
                   The changed properties are provided in the response.
                body:
                    application/json:
                        schema: RuleUpdate
                        example: |
                            {
                                "currentStatus": "enabled"
                            }


    post:
        description: |
          Provides the action to create a new ruleMember in the rule resource
          The only resource type that is allowed to be created is "oic.wk.ruleMember".
          The id of the resource will be generated by the implementation.

        body:
            application/json:
                schema: RuleMember
                example: |
                    {
                      "link": { "href":"coap://mydevice/mybinaryswitch",
                                "if": "oic.if.a",
                                "rt": "oic.r.switch.binary" },
                      "id":       "",
                      "n": "my binary switch (for light bulb) mappings",
                      "memberProperty":  "value",
                      "memberValue":     true
                    }

        responses:
            200:
                description: |
                   Indicates that the target resource was created.
                   The new resource attributes are provided in the response.
                body:
                    application/json:
                       schema: RuleMember
                       example: |
                          {
                            "id": "FFFFB960-FFFF-46F7-BEC0-9E6234671ADC1",
                            "n": "my binary switch (for light bulb) mappings",
                            "link": { "href":"coap://mydevice/mybinaryswitch",
                                "if": "oic.if.a",
                                "rt": "oic.r.switch.binary" },
                            "memberProperty":  "value",
                            "memberValue":     true
                          }

    delete:
        description: |
          No change from collection.
          When delete is used with the URI of the collection without and query parameters then the entire collection is deleted
          When the delete uses the "ins" parameter with the value of a specific link then only that link is deleted
        queryParameters:
          ins:
              type: string
              description: |
                Delete the Web link identified by the string - could be a UUID.
              required: false
              example: |
                DELETE /mycollection?ins="FFFFB960-FFFF-46F7-BEC0-9E6234671ADC1"
        responses:
          200:
            description: The web link instance or the the entire collection has been successfully deleted
          400:
            description: The request is invalid


/RuleMemberResURI:
    description: |
      Rule member resource.
      This resource is assignment statement of an property in a resource indicated by an URI
    displayName: Rule Member

    get:
        description: |
          Provides the rule mappings
        responses:
            200:
                body:
                    application/json:
                       schema: RuleMember
                       example: |
                          {
                            "id": "FFFFB960-FFFF-46F7-BEC0-9E6234671ADC1",
                            "n": "my binary switch (for light bulb) mappings",
                            "link": { "href":"coap://mydevice/mybinaryswitch",
                                "if": "oic.if.a",
                                "rt": "oic.r.switch.binary" },
                            "memberProperty":  "value",
                            "memberValue":     true
                          }
