#%RAML 0.8
title: OICSensorProps
version: v1.1.0-20180115
documentation:
  - title: © 2018 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

schemas:
  - SensorProps: !include oic.r.sensor.props.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.rw","oic.if.baseline"]

/SensorPropsResURI:
  description: |
    This resource describes the properties which guide the reporting of a state change of a Sensor.
    The silenttime represents the period after which a state change report was sent where the Sensor state change is not reported.
    The sensitivity represents the level at which the sensor detects a state change.
    These values are completely dependend on the type of Sensor and the manufacturer capability, so no range restrictions are used.
    The range from the baseresource is only applied to the sensitivity.

  displayName: Sensor Properties
  is: [ interface ] # valid for all methods

  get:
    description: |
      Gets current Sensor Property values
    responses:
      200:
        body:
          application/json:
            schema: SensorProps
            example: |
              {
                "rt":    ["oic.r.sensor.props"],
                "id":    "unique_example_id",
                "silenttime": 10,
                "sensitivity": 20.5,
                "range" :  [ 0, 100 ]
              }
  post:
    description: |
      Sets Sensor Property values
    body:
      application/json:
        schema: SensorProps
        example: |
          {
            "id":         "unique_example_id",
            "silenttime": 20,
            "sensitivity": 10.75
          }
    responses:
      200:
        body:
          application/json:
            schema: SensorProps
            example: |
              {
                "id":          "unique_example_id",
                "silenttime": 20,
                "sensitivity": 10.75
              }