#%RAML 0.8
title: OICValueConditional
version: v1.1.0-20161031
documentation:
  - title: Copyright (c) 2017 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - valueconditional: !include oic.r.value.conditional.json
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.rw","oic.if.baseline"]

/ValueConditionalResURI:
  description: |
    This resource specifies conditions that can be applied to an observed value in any Resource.
    These conditions are applied by the server exposing the Resource to any generated notifications because of subscriptions to the Resource.
    A unicast RETRIEVE to the Resource will receive the most recent value; which may not be the most recent notified value.
    A server exposes this Resource in association with the Resource conveying the observed value.
    This is done by means of a new Resource instance with an RT of ["oic.r.<thing being observed>", "oic.r.value.conditional"], e.g ["oic.r.temperature", "oic.r.value.conditional"].  Please see Section 5.7.1 of the published OCF Resource Type Specification for more details.
    The threshold is the amount by which the thing being observed must change before a notification is sent.
    The minnotifyperiod is the minimum time in ms (milliseconds) that must elapse before a notification is sent.
    If the maxnotifyperiod (time in ms (milliseconds)) elapses then a notification must be sent.
    The maxnotifyperiod timer resets each time a notification is sent.
    A value of '0' for any of threshold, minnotifyperiod or maxnotifyperiod means that the capability is supported but not active.

  displayName: Value Conditional
  is: [ interface ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: valueconditional
            example: |
              {
                "rt":         ["oic.r.value.conditional"],
                "id":         "unique_example_id",
                "threshold":        2,
                "minnotifyperiod":  2000,
                "maxnotifyperiod":  5000
              }

  post:
    description: |
     body:
      application/json:
        schema: valueconditional
        example: |
          {
            "threshold":        2,
            "minnotifyperiod":  1500
          }

    responses:
      200:
        body:
          application/json:
            schema: valueconditional
            example: |
              {
                "threshold":        2,
                "minnotifyperiod":  1500
              }
