#%RAML 0.8
title: OICBodySite
version: v1.1.0-20160519
documentation:
  - title: Copyright (c) 2016 Open Interconnect Consortium, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE OPEN INTERCONNECT CONSORTIUM, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE OPEN INTERCONNECT CONSORTIUM, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - BodySite: !include oic.r.body.site.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.s", "oic.if.baseline"]

/BodySiteResURI:
  description: |
    This resource describes the properties associated with a specific muscle group.
    Body site (bodysite) is a nomenclature code referring a specific muscle group engaged. Refer to Annex C of IEEE Std 11073-10442-2008.
  displayName: Body Site
  is: [ interface ]

  get:
    description: |
      Retrieves a specific muscle group.
    responses:
      200:
        body:
          application/json:
            schema: BodySite
            example: |
              {
                "rt":     ["oic.r.body.site"],
                "id":     "unique_example_id",
                "bodysite": 780,
                "observedtime": "2016-02-15T09:19Z"
              }
